import "dotenv/config";

import { fastify } from "fastify";
import { authRoutes } from "./routes/auth";
import { uploadRoutes } from "./routes/upload";
import { memoriesRoutes } from "./routes/memories";
// cors determines witch URLs can do requests to our backend
import cors from "@fastify/cors";
// JWT (JSON Web Token) is use on our requests to guarantee that the request has done by an authenticated user
import jwt from "@fastify/jwt";
import multipart from "@fastify/multipart";
import staticPath from "@fastify/static";
import { resolve } from "node:path";

// create the application
const app = fastify();

app.register(multipart);
app.register(staticPath, {
  root: resolve(__dirname, "../uploads"),
  prefix: "/uploads",
});
// register routes from separated files
app.register(cors, {
  origin: true, // this allows all the frontend requests
});
app.register(jwt, {
  secret: "spacetime", // a string that will be served as a way to differentiate the JWT generated by this application from other applications. It could be anything (ex: zL9yX#2$r@1m!7q3)
});
app.register(authRoutes);
app.register(uploadRoutes);
app.register(memoriesRoutes);

// start the HTTP server
app
  .listen({
    port: 3333,
    host: "0.0.0.0", // config need to runs the mobile authentication routes
  })
  .then(() => {
    console.log("HTTP server running on http://localhost:3333");
  });
