import "dotenv/config";

import { fastify } from "fastify";
import { authRoutes } from "./routes/auth";
import { memoriesRoutes } from "./routes/memories";
// cors determines witch URLs can do requests to our backend
import cors from "@fastify/cors";
// JWT (JSON Web Token) is use on our requests to guarantee that the request has done by an authenticated user
import jwt from "@fastify/jwt";

// create the application
const app = fastify();

// register routes from separated files
app.register(cors, {
  origin: true, // this allows all the frontend requests
});
app.register(jwt, {
  secret: "spacetime", // a string that will be served as a way to differentiate the JWT generated by this application from other applications. It could be anything (ex: zL9yX#2$r@1m!7q3)
});
app.register(authRoutes);
app.register(memoriesRoutes);

// start the HTTP server
app
  .listen({
    port: 3333,
  })
  .then(() => {
    console.log("HTTP server running on http://localhost:3333");
  });
